In [97]:
import pandas as pd

In [98]:
results = pd.read_csv('results_rossmann.csv', sep=',')

In [99]:
results

,Unnamed: 0,Model,FitTime,PredictionTime,MSE,RMSE,R2,RMSEofMean,Calibration
0,0,"KNeighborsRegressor(algorithm='auto', leaf_siz...",2.709425,3.671832,8.128375e+06,2851.030441,0.458744,0.493791,0.99863

In [68]:
results.drop

<bound method DataFrame.drop of    Unnamed: 0  Unnamed: 0.1  Unnamed: 0.1.1  Model  Fit Time  Prediction Time  \
0           0           NaN             NaN    NaN       NaN              NaN
1           1           NaN             NaN    NaN       NaN              NaN
2           2           NaN             NaN    NaN       NaN              NaN
3           3           NaN             NaN    NaN       NaN              NaN
4           4           NaN             NaN    NaN       NaN              NaN
5           5           NaN             NaN    NaN       NaN              NaN
6           6           NaN             NaN    NaN       NaN              NaN
7           7           NaN             NaN    NaN       NaN              NaN

   MSE  RMSE  R2  RMSE of Mean  Calibration  \
0  NaN   NaN NaN           NaN          NaN
1  NaN   NaN NaN           NaN          NaN
2  NaN   NaN NaN           NaN          NaN
3  NaN   NaN NaN           NaN          NaN
4  NaN   NaN NaN           NaN          NaN
5  NaN   NaN NaN           NaN          NaN
6  NaN   NaN NaN           NaN          NaN
7  NaN   NaN NaN           NaN          NaN

                                                   0
0  KNeighborsRegressor(algorithm='auto', leaf_siz...
1                                 2.8294379711151123
2                                  4.255628824234009
3                                     8128374.577187
4                                   2851.03044129434
5                                0.45874369965767103
6                                0.49379081008183323
7                                 0.9986298423775853  >

In [69]:
double = results.concat(results, ignore_index=True)

AttributeError: 'DataFrame' object has no attribute 'concat'

In [20]:
double

,Unnamed: 0,Unnamed: 0.1,Unnamed: 0.1.1,Model,Fit Time,Prediction Time,MSE,RMSE,R2,RMSE of Mean,Calibration,0
0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"KNeighborsRegressor(algorithm='auto', leaf_siz..."
1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.8294379711151123
2,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.255628824234009
3,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8128374.577187
4,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2851.03044129434
5,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.45874369965767103
6,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.49379081008183323
7,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.9986298423775853
8,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"KNeighborsRegressor(algorithm='auto', leaf_siz..."
9,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.8294379711151123
10,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.255628824234009
11,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8128374.577187
12,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2851.03044129434
13,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.45874369965767103
14,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.49379081008183323
15,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.9986298423775853

In [23]:
result = [1,2,3,4,5,6,7,8]

In [29]:
result.reshape(-1,1)

AttributeError: 'list' object has no attribute 'reshape'

In [33]:
df2 = pd.DataFrame(result)

In [36]:
df.append(df2)
df

   0
0  1
1  2
2  3
3  4
4  5
5  6
6  7
7  8

In [38]:
old_data_frame = pd.DataFrame([[0,'abcd',0,1,123]],columns=['a','b','c','d','e'])

In [74]:
new_record = pd.DataFrame([[0,'abcd',0,1,123]],columns=['a','b','c','d','e'])

old_data_frame = pd.concat([old_data_frame,new_record])

In [44]:
old_data_frame

   a     b  c  d    e
0  0  abcd  0  1  123
0  0  abcd  0  1  123
0  0  abcd  0  1  123
0  0  abcd  0  1  123

In [86]:
#results = pd.read_csv('results_rossmann.csv')

new_record = pd.DataFrame([['Model', 1, 2, 3, 4, 5, 6, 7]], columns=['Model','FitTime','PredictionTime','MSE','RMSE','R2','RMSEofMean','Calibration'])

results = pd.concat([results, new_record])
results

   Model  FitTime  PredictionTime  MSE  RMSE  R2  RMSEofMean  Calibration
0  Model        1               2    3     4   5           6            7

In [82]:
results = pd.read_csv('results_rossmann.csv')
results

,Unnamed: 0,Unnamed: 0.1,Unnamed: 0.1.1,Model,Fit Time,Prediction Time,MSE,RMSE,R2,RMSE of Mean,Calibration,0
0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"KNeighborsRegressor(algorithm='auto', leaf_siz..."
1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.8294379711151123
2,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.255628824234009
3,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8128374.577187
4,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2851.03044129434
5,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.45874369965767103
6,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.49379081008183323
7,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.9986298423775853

In [73]:
new_record = pd.DataFrame([['Model', 1, 2, 3, 4, 5, 6, 7]], columns=['Model','FitTime','PredictionTime','MSE','RMSE','R2','RMSEofMean','Calibration')]
new_record

SyntaxError: invalid syntax (<ipython-input-73-9eded3b5b70a>, line 1)

In [ ]:
results = pd.concat([results, new_record])
results

In [96]:
results.to_csv('results_rossmann.csv')

In [90]:
results = results.drop(0)

In [95]:
results = pd.DataFrame()

In [56]:
df

Empty DataFrame
Columns: []
Index: []

In [61]:
df(columns='Model','FitTime','PredictionTime','MSE','RMSE','R2','RMSEofMean','Calibration')

SyntaxError: positional argument follows keyword argument (<ipython-input-61-bba7b2513219>, line 1)